[package]
name = "glint"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
once_cell = "1.21.3"
onig = { version = "6.5.1", default-features = false }
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.23"
