### desc

[[rules]]
regexp = '(?<=\s)(YES|TRUE)(?=\s)'
color = "green"

[[rules]]
regexp = '(?<=\s)(NO|FALSE)(?=\s)'
color = "yellow"

[[rules]]
regexp = '(?<=\s)PRI(MARY)?(?=\s)'
color = "bold red"

[[rules]]
regexp = '(?<=\s)(MUL|UNI)(?=\s)'
color = "magenta"

[[rules]]
regexp = '(?<=\s)auto_increment(?=\s)'
color = "red"

### Label

[[rules]]
comment = "the colon following each key name"
regexp = '(?<=\b[a-zA-Z0-9_]+):'
color = "blue"

### Table

[[rules]]
comment = "table frame parts"
regexp = ['^\|', '\|$', '(?<=\s)\|(?=\s)', '^\+[\+\-]+\+$']
color = "blue"

### MySQL

[[rules]]
comment = "row separater"
regexp = '^\*{8,} \d+\. row \*{8,}$'
color = "magenta"

[[rules]]
regexp = '^\d+ rows? in set \([\d\.]+ sec\)'
color = "blue"

### data types

[[rules]]
comment = "Email address"
regexp = '[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}'
color = "underline cyan"

[[rules]]
comment = "URI"
regexp = '(?:[a-z][a-z0-9+.-]*):\/\/[^\s/$.?#].[^\s]*'
color = "underline cyan"

[[rules]]
comment = "MAC address"
regexp = '(?:[0-9A-Fa-f]{2}[:-]){5}[0-9A-Fa-f]{2}'
color = "cyan"

[[rules]]
comment = "IP address"
regexp = [
  '(?:\d{1,3}\.){3}\d{1,3}(?::\d+)?', # v4
  '\[[A-Fa-f0-9:]{2,}\](?::\d+)?',    # v6
]
color = "cyan"

[[rules]]
comment = "date"
regexp = '(?<=\s)\d{4}-[01]\d-[0123]\d(?=\s|$)'
color = "green"

[[rules]]
comment = "time"
regexp = '(?<=\s)[0-2]\d:\d{2}:\d{2}(?=\s|$)'
color = "yellow"

[[rules]]
comment = "numeric"
regexp = '(?<=\s)-?\d+(?:\.\d+)?(?=\s|$)'
color = "magenta"

[[rules]]
comment = "semantic version"
regexp = '(?<=\s)\d+\.\d+\.\d+(?=\s|$)'
color = "green"

[[rules]]
regexp = '(?<=\s)NULL(?=\s|$)'
color = "blue"

[[rules]]
comment = "horizontal border"
regexp = '^\-{4,}$'
color = "magenta"
